### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ' '

### ISSUE THREAD

**Issue by shivshaktiss17** [speed8928/IMELE#4]
`Traceback (most recent call last):
  File "/content/IMELE/train.py", line 221, in <module>
    main()
  File "/content/IMELE/train.py", line 82, in main
    train_loader = loaddata.getTrainingData(batch_size,args.csv)
  File "/content/IMELE/loaddata.py", line 69, in getTrainingData
    __imagenet_stats['std'])
  File "/content/IMELE/loaddata.py", line 15, in __init__
    self.frame = pd.read_csv(csv_file, header=None)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: ''`

While running **python train.py** I am getting this file **error**.
Is there any other method change that I need to change, or I am doing something wrong?
Is there any file I need to add?

Please help me.

**Comment by speed8928** [comment]
You need to download the dataset and organize the directory as same as in csv.
